import withPWAInit from 'next-pwa';
import defaultCache from 'next-pwa/cache.js';

// next-pwa's default runtime caching stores /api/ responses in a `apis` cache.
// Every endpoint here is per-user and auth'd, so a cached response could be
// replayed after logout or for a different account. Serve the API from the
// network only and let the app surface its own offline state.
const runtimeCaching = defaultCache.filter((entry) => entry.options?.cacheName !== 'apis');

const withPWA = withPWAInit({
  dest: 'public',
  register: true,
  skipWaiting: true,
  runtimeCaching,
  // next-pwa is webpack-based, so the service worker cannot be generated by
  // `next dev`. Keep it off in development and test the PWA against `next build`.
  disable: process.env.NODE_ENV === 'development',
  buildExcludes: [/middleware-manifest\.json$/],
});

/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
};

export default withPWA(nextConfig);
