import withPWAInit from 'next-pwa';
import defaultCache from 'next-pwa/cache.js';

// next-pwa's default runtime caching stores /api/ responses in a `apis` cache.
// Every endpoint here is per-user and auth'd, so a cached response could be
// replayed after logout or for a different account. Serve the API from the
// network only and let the app surface its own offline state.
const runtimeCaching = defaultCache.filter((entry) => entry.options?.cacheName !== 'apis');

const withPWA = withPWAInit({
  dest: 'public',
  register: true,
  skipWaiting: true,
  runtimeCaching,
  // next-pwa is webpack-based, so the service worker cannot be generated by
  // `next dev`. Keep it off in development and test the PWA against `next build`.
  disable: process.env.NODE_ENV === 'development',
  buildExcludes: [/middleware-manifest\.json$/],
});

// The browser talks to Supabase directly (auth + token refresh), so its origin
// has to be reachable from connect-src. Everything else is same-origin.
const supabaseOrigin = process.env.NEXT_PUBLIC_SUPABASE_URL
  ? new URL(process.env.NEXT_PUBLIC_SUPABASE_URL).origin
  : '';
const isDev = process.env.NODE_ENV === 'development';

// Next inlines its bootstrap and flight payload as <script> tags. Emitting a
// per-request nonce needs middleware, which would opt every page out of static
// rendering, so 'unsafe-inline' stays for scripts. Tailwind ships as a
// stylesheet but next-themes writes an inline style attribute, hence the same
// allowance for styles. Everything that is not needed is denied outright.
const csp = [
  "default-src 'self'",
  `script-src 'self' 'unsafe-inline'${isDev ? " 'unsafe-eval'" : ''}`,
  "style-src 'self' 'unsafe-inline'",
  "img-src 'self' data: blob:",
  "font-src 'self' data:",
  `connect-src 'self' ${supabaseOrigin} ${isDev ? 'ws: http://localhost:*' : ''}`.trim(),
  "worker-src 'self'",
  "manifest-src 'self'",
  "object-src 'none'",
  "base-uri 'none'",
  "form-action 'self'",
  "frame-ancestors 'none'",
  ...(isDev ? [] : ['upgrade-insecure-requests']),
].join('; ');

const securityHeaders = [
  { key: 'Content-Security-Policy', value: csp },
  { key: 'X-Frame-Options', value: 'DENY' },
  { key: 'X-Content-Type-Options', value: 'nosniff' },
  { key: 'Referrer-Policy', value: 'strict-origin-when-cross-origin' },
  { key: 'Permissions-Policy', value: 'camera=(), microphone=(), geolocation=(), payment=()' },
  { key: 'Cross-Origin-Opener-Policy', value: 'same-origin' },
  // HSTS is only meaningful over TLS and would poison localhost, so it is
  // production-only.
  ...(isDev
    ? []
    : [{ key: 'Strict-Transport-Security', value: 'max-age=63072000; includeSubDomains; preload' }]),
];

/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  poweredByHeader: false,
  async headers() {
    return [{ source: '/:path*', headers: securityHeaders }];
  },
};

export default withPWA(nextConfig);
